import React, { Suspense } from 'react';
import { MagicWandIcon } from 'ui';

import { allUseCases } from '@/.contentlayer/generated';
import Cta from '@/components/cta';
import { PageIntro } from '@/components/page-intro';
import UseCases from '@/components/sections/use-cases/use-cases';

export const metadata = {
  title: 'Use Cases',
  description:
    'We believe in efficiency and maximizing our resources to provide the best value to our clients.',
};

function UseCase() {
  return (
    <main>
      <Suspense fallback={<div>waiting for samuel to push a commit</div>}>
        <PageIntro
          eyebrow="Use Cases"
          title="AI that amplifies human creativity"
        >
          <p className="text-muted-foreground">
            Pretty soon, most of what you see online will be generated by AI. It
            will get harder for visionary creators like you to stand out. With
            And Voila AI, you have the power to thrive in a world of synthetic
            content. Our technology aims to amplify what makes you
            extraordinary.
          </p>
        </PageIntro>
        <Suspense fallback={<div>Loading...</div>}>
          <UseCases useCases={allUseCases} />
        </Suspense>
        <Cta
          title="Power up your creativity"
          text="See firsthand how And Voila AI can enhance your creative process. Sign up now and try for yourself."
          linkHref="/sign-up"
          buttonText="Sign Up Free"
          buttonIcon={<MagicWandIcon />}
          footerText="No credit card required"
        />
      </Suspense>
    </main>
  );
}

export default UseCase;
