import { Metadata } from 'next';
import React, { Suspense } from 'react';
import { MagicWandIcon } from 'ui';

import { allUseCases } from '@/.contentlayer/generated';
import Cta from '@/components/cta';
import { PageIntro } from '@/components/page-intro';
import UseCases from '@/components/sections/use-cases/use-cases';
import { SITE_URL } from '@/lib/constants';

export function generateMetadata(): Metadata {
  const title = 'Use Cases';
  const description =
    "See how the world's top creators use And Voila to glow up their content, save time, and keep their IP safe. Your ideas supercharged, all the way to the bank.";

  const url = `${SITE_URL}/use-cases`;
  const openGraphImage = '/open-graph.jpg';

  const metadata = {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      images: openGraphImage,
    },
    twitter: {
      title,
      description,
      images: openGraphImage,
    },
  };

  return metadata;
}

function UseCase() {
  return (
    <main>
      <Suspense fallback={<div>waiting for samuel to push a commit</div>}>
        <PageIntro
          eyebrow="Use Cases"
          title="AI that amplifies human creativity"
        >
          <p className="text-muted-foreground">
            Pretty soon, most of what you see online will be generated by AI. It
            will get harder for visionary creators like you to stand out. With
            And Voila AI, you have the power to thrive in a world of synthetic
            content. Our technology aims to amplify what makes you
            extraordinary.
          </p>
        </PageIntro>
        <Suspense fallback={<div>Loading...</div>}>
          <UseCases useCases={allUseCases} />
        </Suspense>
        <Cta
          title="Power up your creativity"
          text="See firsthand how And Voila AI can enhance your creative process. Sign up now and try for yourself."
          linkHref="https://app.andvoila.ai/sign-up"
          buttonText="Sign Up Free"
          buttonIcon={<MagicWandIcon />}
          footerText="No credit card required"
        />
      </Suspense>
    </main>
  );
}

export default UseCase;
